### ISSUE TITLE
Error:  ReferenceError: window is not defined, occurred on server rendering

### ISSUE THREAD

**Issue by cslinmiso** [coderhaoxin/react-flatpickr#67]
This issue happens only on v3.6.4 which upgrades flatpickr and occurred on server rendering.
 
ReferenceError: window is not defined
    at /home/share/node/node_modules/flatpickr/dist/flatpickr.js:454:5
    at /home/share/node/node_modules/flatpickr/dist/flatpickr.js:3:85
    at Object.<anonymous> (/home/share/node/node_modules/flatpickr/dist/flatpickr.js:6:2)

Is there anyway we could do? Thanks

**Comment by cslinmiso** [comment]
related to this issue: https://github.com/flatpickr/flatpickr/issues/1363

**Comment by cslinmiso** [comment]
Fixed on flatpickr v4.4.7
