### ISSUE TITLE
`cannot read property _flatpickr of null` when used in unit tests

### ISSUE THREAD

**Issue by gfarrell** [coderhaoxin/react-flatpickr#7]
When using enzyme's full document rendering in node.js (ie using jsdom to supply a DOM), the following error occurs:

```
     TypeError: Cannot read property '_flatpickr' of null
      at init (node_modules/flatpickr/dist/flatpickr.js:10:14)
      at Object.Flatpickr (node_modules/flatpickr/dist/flatpickr.js:1343:2)
      at DateTimePicker.componentDidMount (node_modules/react-flatpickr/build/index.js:71:24)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:265:25
      at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:264:11
      at CallbackQueue.notifyAll (node_modules/react-dom/lib/CallbackQueue.js:76:22)
      at ReactReconcileTransaction.close (node_modules/react-dom/lib/ReactReconcileTransaction.js:80:26)
      at ReactReconcileTransaction.closeAll (node_modules/react-dom/lib/Transaction.js:206:25)
      at ReactReconcileTransaction.perform (node_modules/react-dom/lib/Transaction.js:153:16)
      at batchedMountComponentIntoNode (node_modules/react-dom/lib/ReactMount.js:126:15)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-dom/lib/Transaction.js:140:20)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:97:27)
      at Object._renderNewRootComponent (node_modules/react-dom/lib/ReactMount.js:320:18)
      at Object._renderSubtreeIntoContainer (node_modules/react-dom/lib/ReactMount.js:401:32)
      at Object.render (node_modules/react-dom/lib/ReactMount.js:422:23)
      at Object.renderIntoDocument (node_modules/react-dom/lib/ReactTestUtils.js:79:21)
      at renderWithOptions (node_modules/enzyme/build/react-compat.js:187:26)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:94:59)
      at mount (node_modules/enzyme/build/mount.js:19:10)
      at fullRender (test/components/registrations_component.spec.js:48:30)
      at Context.<anonymous> (test/components/registrations_component.spec.js:111:25)
```

The problem seems to be that the node isn't defined in `componentDidMount`, and it's currently being set with:

```
var node = document.getElementById(id);
```

This returns null in the jsdom environment for some reason.

**Comment by gfarrell** [comment]
This is because `componentDidMount` is using `document.getElementById`. In fact, using `id` at all is unnecessary, and really should be using `react-dom` instead. I'll make a PR.
